// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TorneoFutbol.App.Persistencia;

namespace TorneoFutbol.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20211128055519_E_Migrant")]
    partial class E_Migrant
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TorneoFutbol.App.Dominio.Entidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion_Electronica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MigranteId")
                        .HasColumnType("int");

                    b.Property<string>("Nit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pagina_Web")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Razon_Social")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sector")
                        .HasColumnType("int");

                    b.Property<string>("Teléfono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo_Servicio")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MigranteId");

                    b.ToTable("Entidades");
                });

            modelBuilder.Entity("TorneoFutbol.App.Dominio.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Cedula_Integrante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre_Grupo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre_Integrante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parentesco")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("TorneoFutbol.App.Dominio.Migrante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion_Electronica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dirección_Actual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha_Nacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GrupoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero_Identificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Situación_Laboral")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Teléfono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo_Identificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId");

                    b.ToTable("Migrantes");
                });

            modelBuilder.Entity("TorneoFutbol.App.Dominio.Necesidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EntidadId")
                        .HasColumnType("int");

                    b.Property<int?>("MigranteId")
                        .HasColumnType("int");

                    b.Property<int>("Nombre_Nesesidad")
                        .HasColumnType("int");

                    b.Property<int>("Prioridad")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EntidadId");

                    b.HasIndex("MigranteId");

                    b.ToTable("Necesidades");
                });

            modelBuilder.Entity("TorneoFutbol.App.Dominio.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Estado_Servicio")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_Fin_Servicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fecha_Inico_Servicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numero_Migrantes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("TorneoFutbol.App.Dominio.Entidad", b =>
                {
                    b.HasOne("TorneoFutbol.App.Dominio.Migrante", "Migrante")
                        .WithMany()
                        .HasForeignKey("MigranteId");

                    b.Navigation("Migrante");
                });

            modelBuilder.Entity("TorneoFutbol.App.Dominio.Migrante", b =>
                {
                    b.HasOne("TorneoFutbol.App.Dominio.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("GrupoId");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("TorneoFutbol.App.Dominio.Necesidad", b =>
                {
                    b.HasOne("TorneoFutbol.App.Dominio.Entidad", "Entidad")
                        .WithMany()
                        .HasForeignKey("EntidadId");

                    b.HasOne("TorneoFutbol.App.Dominio.Migrante", "Migrante")
                        .WithMany()
                        .HasForeignKey("MigranteId");

                    b.Navigation("Entidad");

                    b.Navigation("Migrante");
                });
#pragma warning restore 612, 618
        }
    }
}
